on:
  push:
    branches:
      - abao/dev
name: docs

jobs:
  docs:
    runs-on: ubuntu-latest
    needs: [stylua, lint-check, ruff, test_isolated, integration-tests]
    steps:
      - uses: actions/checkout@v3
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: neopyter
          demojify: true
          treesitter: true
      - name: cat
        run: cat doc/neopyter.txt
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs(vimdoc): auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
